/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavetorial;

/**
 *
 * @author Cristiane Corrêa
 */
public class NewJFrame extends javax.swing.JFrame {
    
    Grelha grelha;
    
        

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        grelha = new Grelha();
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()));
        jTextFieldNrEscala.setText(String.valueOf(grelha.getNescala()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelPainel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxVisibilidade = new javax.swing.JCheckBox();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonMaisZoom = new javax.swing.JButton();
        jButtonMenosZoom = new javax.swing.JButton();
        jButtonMoverBaixo = new javax.swing.JButton();
        jButtonMoverInicio = new javax.swing.JButton();
        jButtonMoverCima = new javax.swing.JButton();
        jButtonMoverDireita = new javax.swing.JButton();
        jButtonMoverEsquerda = new javax.swing.JButton();
        jTextFieldEscala = new javax.swing.JTextField();
        jTextFieldNrEscala = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelPainelLayout = new javax.swing.GroupLayout(jPanelPainel);
        jPanelPainel.setLayout(jPanelPainelLayout);
        jPanelPainelLayout.setHorizontalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanelPainelLayout.setVerticalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Grelha:");

        jLabel2.setText("Escala");

        jLabel3.setText("Nr. Escalas");

        jCheckBoxVisibilidade.setSelected(true);
        jCheckBoxVisibilidade.setText("Visibilidade");
        jCheckBoxVisibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVisibilidadeActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonMaisZoom.setText("Zoom +");
        jButtonMaisZoom.setActionCommand("Zoom+");
        jButtonMaisZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisZoomActionPerformed(evt);
            }
        });

        jButtonMenosZoom.setText("Zoom -");
        jButtonMenosZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosZoomActionPerformed(evt);
            }
        });

        jButtonMoverBaixo.setText("V");
        jButtonMoverBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverBaixoActionPerformed(evt);
            }
        });

        jButtonMoverInicio.setText("O");
        jButtonMoverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverInicioActionPerformed(evt);
            }
        });

        jButtonMoverCima.setText("^");
        jButtonMoverCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverCimaActionPerformed(evt);
            }
        });

        jButtonMoverDireita.setText(">");
        jButtonMoverDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverDireitaActionPerformed(evt);
            }
        });

        jButtonMoverEsquerda.setText("<");
        jButtonMoverEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverEsquerdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNrEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxVisibilidade)
                                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonMoverEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonMoverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonMoverCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonMoverBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonMoverDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonMaisZoom))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addComponent(jButtonMenosZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNrEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxVisibilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jButtonMoverCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMaisZoom)
                            .addComponent(jButtonMoverInicio)
                            .addComponent(jButtonMoverDireita)
                            .addComponent(jButtonMoverEsquerda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMenosZoom)
                            .addComponent(jButtonMoverBaixo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizar)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jCheckBoxVisibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVisibilidadeActionPerformed
        // TODO add your handling code here:
        
        grelha.setVisivel(jCheckBoxVisibilidade.isVisible());
        desenhaSistem2D();
    }//GEN-LAST:event_jCheckBoxVisibilidadeActionPerformed

    private void jButtonMoverEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverEsquerdaActionPerformed
        // TODO add your handling code here:
        grelha.setXini(grelha.getXini() + grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverEsquerdaActionPerformed

    private void jButtonMoverCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverCimaActionPerformed
        // TODO add your handling code here:
        grelha.setYini(grelha.getYini() + grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverCimaActionPerformed

    private void jButtonMoverDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverDireitaActionPerformed
        // TODO add your handling code here:
        grelha.setXini(grelha.getXini() - grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverDireitaActionPerformed

    private void jButtonMoverBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverBaixoActionPerformed
        // TODO add your handling code here:
        grelha.setYini(grelha.getYini() - grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverBaixoActionPerformed

    private void jButtonMoverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverInicioActionPerformed
        // TODO add your handling code here:
        
        grelha.setXini(0);
        grelha.setYini(0);
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverInicioActionPerformed

    private void jButtonMaisZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisZoomActionPerformed
        // TODO add your handling code here:
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()+5));
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMaisZoomActionPerformed

    private void jButtonMenosZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosZoomActionPerformed
        // TODO add your handling code here:
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()-5));
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMenosZoomActionPerformed

    
    public void desenhaSistem2D(){
        
        grelha.setEscala(Integer.parseInt(jTextFieldEscala.getText()));
        grelha.setNescala(Integer.parseInt(jTextFieldNrEscala.getText()));
        grelha.setVisivel(jCheckBoxVisibilidade.isSelected());
        
        grelha.desenhaGrelha(jPanelPainel.getGraphics());
    }
    
   /*     private void ResetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        invalidate();
        validate();
        repaint();
    }*/  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonMaisZoom;
    private javax.swing.JButton jButtonMenosZoom;
    private javax.swing.JButton jButtonMoverBaixo;
    private javax.swing.JButton jButtonMoverCima;
    private javax.swing.JButton jButtonMoverDireita;
    private javax.swing.JButton jButtonMoverEsquerda;
    private javax.swing.JButton jButtonMoverInicio;
    private javax.swing.JCheckBox jCheckBoxVisibilidade;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JTextField jTextFieldEscala;
    private javax.swing.JTextField jTextFieldNrEscala;
    // End of variables declaration//GEN-END:variables
}
