/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemavetorial;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Cristiane Corrêa
 */
public class NewJFrame extends javax.swing.JFrame {
    
    Grelha grelha;
    DefaultListModel listModel;
    ArrayList listaFiguras;
        

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        grelha = new Grelha();
        
        listaFiguras = new ArrayList();
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()));
        jTextFieldNrEscala.setText(String.valueOf(grelha.getNescala()));
        
        listModel = new DefaultListModel();
        jList1.setModel(listModel);
        
        jButtonRemoverFigura.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanelPainel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxVisibilidade = new javax.swing.JCheckBox();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonMaisZoom = new javax.swing.JButton();
        jButtonMenosZoom = new javax.swing.JButton();
        jButtonMoverBaixo = new javax.swing.JButton();
        jButtonMoverInicio = new javax.swing.JButton();
        jButtonMoverCima = new javax.swing.JButton();
        jButtonMoverDireita = new javax.swing.JButton();
        jButtonMoverEsquerda = new javax.swing.JButton();
        jTextFieldEscala = new javax.swing.JTextField();
        jTextFieldNrEscala = new javax.swing.JTextField();
        jRadioButtonLinha = new javax.swing.JRadioButton();
        jRadioButtonTriangulo = new javax.swing.JRadioButton();
        jRadioButtonCirculo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonAdicionarFigura = new javax.swing.JButton();
        jButtonRemoverFigura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelPainelLayout = new javax.swing.GroupLayout(jPanelPainel);
        jPanelPainel.setLayout(jPanelPainelLayout);
        jPanelPainelLayout.setHorizontalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jPanelPainelLayout.setVerticalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Grelha:");

        jLabel2.setText("Escala");

        jLabel3.setText("Nr. Escalas");

        jCheckBoxVisibilidade.setSelected(true);
        jCheckBoxVisibilidade.setText("Visibilidade");
        jCheckBoxVisibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVisibilidadeActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonMaisZoom.setText("Zoom +");
        jButtonMaisZoom.setActionCommand("Zoom+");
        jButtonMaisZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisZoomActionPerformed(evt);
            }
        });

        jButtonMenosZoom.setText("Zoom -");
        jButtonMenosZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosZoomActionPerformed(evt);
            }
        });

        jButtonMoverBaixo.setText("V");
        jButtonMoverBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverBaixoActionPerformed(evt);
            }
        });

        jButtonMoverInicio.setText("O");
        jButtonMoverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverInicioActionPerformed(evt);
            }
        });

        jButtonMoverCima.setText("^");
        jButtonMoverCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverCimaActionPerformed(evt);
            }
        });

        jButtonMoverDireita.setText(">");
        jButtonMoverDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverDireitaActionPerformed(evt);
            }
        });

        jButtonMoverEsquerda.setText("<");
        jButtonMoverEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverEsquerdaActionPerformed(evt);
            }
        });

        jTextFieldNrEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNrEscalaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLinha);
        jRadioButtonLinha.setText("Linha");
        jRadioButtonLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLinhaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTriangulo);
        jRadioButtonTriangulo.setText("Triângulo");

        buttonGroup1.add(jRadioButtonCirculo);
        jRadioButtonCirculo.setText("Circulo");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButtonAdicionarFigura.setText("Adicionar");
        jButtonAdicionarFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarFiguraActionPerformed(evt);
            }
        });

        jButtonRemoverFigura.setText("Remover");
        jButtonRemoverFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverFiguraActionPerformed(evt);
            }
        });

        jLabel4.setText("Figuras:");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxVisibilidade)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNrEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAdicionarFigura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButtonLinha)
                                    .addComponent(jRadioButtonTriangulo)
                                    .addComponent(jRadioButtonCirculo)
                                    .addComponent(jLabel4)
                                    .addComponent(jButtonRemoverFigura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMoverEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonMoverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonMoverCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonMoverBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMoverDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonMaisZoom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonMenosZoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanelPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNrEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jCheckBoxVisibilidade)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonLinha)
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButtonTriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonCirculo)
                                .addGap(13, 13, 13)
                                .addComponent(jButtonAdicionarFigura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoverFigura))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMoverCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMoverInicio)
                            .addComponent(jButtonMoverDireita)
                            .addComponent(jButtonMoverEsquerda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMoverBaixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonMaisZoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMenosZoom)
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jCheckBoxVisibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVisibilidadeActionPerformed
        // TODO add your handling code here:
        
        grelha.setVisivel(jCheckBoxVisibilidade.isVisible());
        desenhaSistem2D();
    }//GEN-LAST:event_jCheckBoxVisibilidadeActionPerformed

    private void jButtonMoverEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverEsquerdaActionPerformed
        // TODO add your handling code here:
        grelha.setXini(grelha.getXini() - grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverEsquerdaActionPerformed

    private void jButtonMoverCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverCimaActionPerformed
        // TODO add your handling code here:
        grelha.setYini(grelha.getYini() - grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverCimaActionPerformed

    private void jButtonMoverDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverDireitaActionPerformed
        // TODO add your handling code here:
        grelha.setXini(grelha.getXini() + grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverDireitaActionPerformed

    private void jButtonMoverBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverBaixoActionPerformed
        // TODO add your handling code here:
        grelha.setYini(grelha.getYini() + grelha.getEscala());
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverBaixoActionPerformed

    private void jButtonMoverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverInicioActionPerformed
        // TODO add your handling code here:
        
        grelha.setXini(0);
        grelha.setYini(0);
        
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMoverInicioActionPerformed

    private void jButtonMaisZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisZoomActionPerformed
        // TODO add your handling code here:
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()+5));
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMaisZoomActionPerformed

    private void jButtonMenosZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosZoomActionPerformed
        // TODO add your handling code here:
        
        jTextFieldEscala.setText(String.valueOf(grelha.getEscala()-5));
        desenhaSistem2D();
    }//GEN-LAST:event_jButtonMenosZoomActionPerformed

    private void jTextFieldNrEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNrEscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNrEscalaActionPerformed

    private void jRadioButtonLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLinhaActionPerformed

    private void jButtonAdicionarFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarFiguraActionPerformed
        // TODO add your handling code here:
        
        if(jRadioButtonLinha.isSelected()){
        //listModel.addElement("Linha");
            
        Linha novaLinha = new Linha(grelha);
        
        boolean introducaoCorretaDeDados = novaLinha.executaInterface();
        
        if ( introducaoCorretaDeDados ) {
            
            novaLinha.desenha(jPanelPainel.getGraphics());
             
            listaFiguras.add(novaLinha);
            listModel.addElement(novaLinha.informacao());
        }else{
            JOptionPane.showMessageDialog(this, "Coordenadas Incorretas", 
                    
                    "Adicionar Linha", JOptionPane.INFORMATION_MESSAGE);
        }
       }
        
        if(jRadioButtonTriangulo.isSelected()){
            //listModel.addElement("Triangulo");
            
            Triangulo novoTriangulo = new Triangulo(grelha);
            
            boolean introdcaoCorretaDeDados = novoTriangulo.executaInterface();
            
            if ( introdcaoCorretaDeDados ) {
                
                novoTriangulo.desenha(jPanelPainel.getGraphics());
                
                listaFiguras.add(novoTriangulo);
                listModel.addElement(novoTriangulo.informacao());
            } else {
                JOptionPane.showMessageDialog(this, "Coordenadas Icorretas",
                        "Adicionar Linha", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        if(jRadioButtonCirculo.isSelected()){
           // listModel.addElement("Circulo");
           
            Circulo novoCirculo = new Circulo(grelha);
            
            boolean introdcaoCorretaDeDados = novoCirculo.executaInterface();
            
            if ( introdcaoCorretaDeDados ) {
                
                novoCirculo.desenha(jPanelPainel.getGraphics());
                
                listaFiguras.add(novoCirculo);
                listModel.addElement(novoCirculo.informacao());
            } else {
                JOptionPane.showMessageDialog(this, "Coordenadas Icorretas",
                        "Adicionar Linha", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        
        if(!jButtonRemoverFigura.isEnabled()){
            jButtonRemoverFigura.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAdicionarFiguraActionPerformed

    private void jButtonRemoverFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverFiguraActionPerformed
        // TODO add your handling code here:
        if(jList1.getSelectedIndex() == -1){
           JOptionPane.showMessageDialog(this, "Primeiro tem que selecionar uma figura na lista", "Remover figura ",
                          JOptionPane.INFORMATION_MESSAGE);
        }else{
            int indice = jList1.getSelectedIndex();
            listModel.remove(indice);
            listaFiguras.remove(indice);
            desenhaSistem2D();
        }
        
        if ( listModel.isEmpty()){
             jButtonRemoverFigura.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonRemoverFiguraActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        int indice = jList1.getSelectedIndex();
        if ( indice != -1 ){
            Figura f = (Figura) listaFiguras.get(indice);
            f.setSelecionada(true);
            desenhaSistem2D();
            f.setSelecionada(false);
        }
    }//GEN-LAST:event_jList1MouseClicked

    
    public void desenhaSistem2D(){
        
        grelha.setEscala(Integer.parseInt(jTextFieldEscala.getText()));
        grelha.setNescala(Integer.parseInt(jTextFieldNrEscala.getText()));
        grelha.setVisivel(jCheckBoxVisibilidade.isSelected());
        
        grelha.desenhaGrelha(jPanelPainel.getGraphics());
        
        for (int i = 0; i < listaFiguras.size(); i++) {
            Figura f = (Figura) listaFiguras.get(i);
            f.desenha(jPanelPainel.getGraphics());
        }
    }
    
   /*     private void ResetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        invalidate();
        validate();
        repaint();
    }*/  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButtonAdicionarFigura;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonMaisZoom;
    private javax.swing.JButton jButtonMenosZoom;
    private javax.swing.JButton jButtonMoverBaixo;
    private javax.swing.JButton jButtonMoverCima;
    private javax.swing.JButton jButtonMoverDireita;
    private javax.swing.JButton jButtonMoverEsquerda;
    private javax.swing.JButton jButtonMoverInicio;
    private javax.swing.JButton jButtonRemoverFigura;
    private javax.swing.JCheckBox jCheckBoxVisibilidade;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JRadioButton jRadioButtonCirculo;
    private javax.swing.JRadioButton jRadioButtonLinha;
    private javax.swing.JRadioButton jRadioButtonTriangulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEscala;
    private javax.swing.JTextField jTextFieldNrEscala;
    // End of variables declaration//GEN-END:variables
}
